### ISSUE TITLE
Problem on send report_coverage file to CI becaus file not found

### ISSUE THREAD

**Issue by andreleoni** [rdunlop/codeclimate_circle_ci_coverage#6]
Hello, I'm getting the follow error on circleCI

```
#!/bin/bash -eo pipefail
bundle exec report_coverage
Coverage report generated for RSpec to /tmp/coverage. 0.0 / 0.0 LOC (100.0%) covered.
bundler: failed to load command: report_coverage (/home/circleci/website/vendor/bundle/ruby/2.4.0/bin/report_coverage)
CodeClimate::TestReporter::InvalidPayload: No source files were found in the test report payload
```

my circleci is v2, follow, my 

```
version: 2
jobs:
  build:
    environment:
      - RAILS_ENV: "test"
      - CI: true
    working_directory: ~/website
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          command: sudo apt-get install nodejs

      - run:
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3

      - run:
          name: precompile
          command: bundle exec rake assets:precompile

      - run:
          name: Specs
          command: bundle exec rspec

      - store_artifacts:
          path: coverage/.resultset.json
          prefix: coverage

      - deploy:
          name: Merge and copy coverage data
          command: bundle exec report_coverage

```

my rspec is working fine, and the coverage files would be generating of course...

my project: https://github.com/andreleoni/exchange-app
